package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "generate:reset"

type targetStruct struct {
	Name string
	Type *ast.StructType
}

type packageData struct {
	Dir     string
	Name    string
	Structs []targetStruct
	Methods map[string]struct{}
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		fatalf("get working directory: %v", err)
	}

	packages, err := collectPackages(root)
	if err != nil {
		fatalf("collect packages: %v", err)
	}

	for _, pkg := range packages {
		if len(pkg.Structs) == 0 {
			continue
		}

		if err := writeGeneratedFile(pkg); err != nil {
			fatalf("write generated file for %s: %v", pkg.Dir, err)
		}
	}
}

func collectPackages(root string) ([]packageData, error) {
	var dirs []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !d.IsDir() {
			return nil
		}

		name := d.Name()
		if name == ".git" || name == "vendor" {
			return filepath.SkipDir
		}

		dirs = append(dirs, path)
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Strings(dirs)

	var out []packageData
	for _, dir := range dirs {
		pkgs, err := parser.ParseDir(token.NewFileSet(), dir, func(info fs.FileInfo) bool {
			name := info.Name()
			if strings.HasSuffix(name, "_test.go") {
				return false
			}
			return strings.HasSuffix(name, ".go")
		}, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		if len(pkgs) == 0 {
			continue
		}

		names := make([]string, 0, len(pkgs))
		for name := range pkgs {
			names = append(names, name)
		}
		sort.Strings(names)

		for _, name := range names {
			pkg := pkgs[name]
			data := packageData{
				Dir:     dir,
				Name:    name,
				Methods: collectResetMethods(pkg),
			}

			for _, file := range pkg.Files {
				for _, decl := range file.Decls {
					genDecl, ok := decl.(*ast.GenDecl)
					if !ok || genDecl.Tok != token.TYPE {
						continue
					}

					for _, spec := range genDecl.Specs {
						typeSpec, ok := spec.(*ast.TypeSpec)
						if !ok {
							continue
						}
						structType, ok := typeSpec.Type.(*ast.StructType)
						if !ok {
							continue
						}
						if !hasMarkerComment(genDecl.Doc, typeSpec.Doc) {
							continue
						}
						if _, exists := data.Methods[typeSpec.Name.Name]; exists {
							continue
						}

						data.Structs = append(data.Structs, targetStruct{
							Name: typeSpec.Name.Name,
							Type: structType,
						})
					}
				}
			}

			sort.Slice(data.Structs, func(i, j int) bool {
				return data.Structs[i].Name < data.Structs[j].Name
			})

			if len(data.Structs) > 0 {
				out = append(out, data)
			}
		}
	}

	return out, nil
}

func collectResetMethods(pkg *ast.Package) map[string]struct{} {
	result := make(map[string]struct{})
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			f, ok := decl.(*ast.FuncDecl)
			if !ok || f.Recv == nil || f.Name == nil || f.Name.Name != "Reset" {
				continue
			}
			if len(f.Recv.List) == 0 {
				continue
			}

			recvName := receiverTypeName(f.Recv.List[0].Type)
			if recvName == "" {
				continue
			}
			result[recvName] = struct{}{}
		}
	}
	return result
}

func receiverTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func hasMarkerComment(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, c := range group.List {
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if text == marker {
				return true
			}
		}
	}
	return false
}

func writeGeneratedFile(pkg packageData) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg.Name)
	b.WriteString("\n\n")

	for i, s := range pkg.Structs {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(generateMethod(s))
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return err
	}

	targetPath := filepath.Join(pkg.Dir, "reset.gen.go")
	current, err := os.ReadFile(targetPath)
	if err == nil && bytes.Equal(current, src) {
		return nil
	}
	if err := os.WriteFile(targetPath, src, 0o644); err != nil {
		return err
	}

	return nil
}

func generateMethod(s targetStruct) string {
	recv := receiverName(s.Name)
	var b strings.Builder
	fmt.Fprintf(&b, "func (%s *%s) Reset() {\n", recv, s.Name)
	fmt.Fprintf(&b, "\tif %s == nil {\n\t\treturn\n\t}\n\n", recv)

	for _, field := range s.Type.Fields.List {
		fieldNames := fieldNames(field)
		for _, name := range fieldNames {
			path := recv + "." + name
			writeResetCode(&b, path, field.Type, 1)
		}
	}

	b.WriteString("}\n")
	return b.String()
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) == 0 {
		if name := embeddedFieldName(field.Type); name != "" {
			return []string{name}
		}
		return nil
	}
	out := make([]string, 0, len(field.Names))
	for _, n := range field.Names {
		out = append(out, n.Name)
	}
	return out
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedFieldName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	}
	return ""
}

func writeResetCode(b *strings.Builder, target string, typ ast.Expr, indent int) {
	switch t := typ.(type) {
	case *ast.StarExpr:
		writeIndent(b, indent)
		fmt.Fprintf(b, "if %s != nil {\n", target)
		writeIndent(b, indent+1)
		fmt.Fprintf(b, "if resetter, ok := any(%s).(interface{ Reset() }); ok {\n", target)
		writeIndent(b, indent+2)
		b.WriteString("resetter.Reset()\n")
		writeIndent(b, indent+1)
		b.WriteString("} else {\n")
		writeResetCode(b, "(*"+target+")", t.X, indent+2)
		writeIndent(b, indent+1)
		b.WriteString("}\n")
		writeIndent(b, indent)
		b.WriteString("}\n")
	case *ast.ArrayType:
		if t.Len == nil {
			writeIndent(b, indent)
			fmt.Fprintf(b, "%s = (%s)[:0]\n", target, target)
			return
		}
		writeZeroValueAssignment(b, target, typ, indent)
	case *ast.MapType:
		writeIndent(b, indent)
		fmt.Fprintf(b, "clear(%s)\n", target)
	default:
		writeIndent(b, indent)
		fmt.Fprintf(b, "if resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", target)
		writeIndent(b, indent+1)
		b.WriteString("resetter.Reset()\n")
		writeIndent(b, indent)
		b.WriteString("} else {\n")
		writeZeroValueAssignment(b, target, typ, indent+1)
		writeIndent(b, indent)
		b.WriteString("}\n")
	}
}

func writeZeroValueAssignment(b *strings.Builder, target string, typ ast.Expr, indent int) {
	writeIndent(b, indent)
	fmt.Fprintf(b, "var zero %s\n", nodeString(typ))
	writeIndent(b, indent)
	fmt.Fprintf(b, "%s = zero\n", target)
}

func nodeString(expr ast.Expr) string {
	var b bytes.Buffer
	_ = printer.Fprint(&b, token.NewFileSet(), expr)
	return b.String()
}

func receiverName(typeName string) string {
	if typeName == "" {
		return "s"
	}

	var out []rune
	for _, r := range typeName {
		if r >= 'A' && r <= 'Z' {
			out = append(out, r+'a'-'A')
		} else if r >= 'a' && r <= 'z' {
			out = append(out, r)
		}
		if len(out) == 2 {
			break
		}
	}
	if len(out) == 0 {
		return "s"
	}
	return string(out)
}

func writeIndent(b *strings.Builder, indent int) {
	for i := 0; i < indent; i++ {
		b.WriteByte('\t')
	}
}

func fatalf(formatStr string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, formatStr+"\n", args...)
	os.Exit(1)
}
